import initHeader from "./modules/linksHeader.js";
initHeader();
import initOrcamento from "./modules/orcamento.js";
initOrcamento();
import initPerguntas from "./modules/perguntasFrequentes.js";
initPerguntas();
import initGaleria from "./modules/galeriaImagens.js";
initGaleria();
import initAnimation from "./modules/animacao.js";
initAnimation();
import initMeuMobile from "./modules/menu-mobile.js";
initMeuMobile();
